1.4.5

In [39]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [29]:

img = cv2.imread('j.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [38]:
img = cv2.imread('j.png',0)
kernel = np.ones((5,5),np.uint8)
dilation = cv2.dilate(img,kernel,iterations = 1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
img = cv2.imread('j.png',0)
kernel = np.ones((5,5),np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
dilation = cv2.dilate(img,kernel,iterations = 1)

In [36]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

In [37]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [9]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [10]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [12]:
# Rectangular Kernel
>>> cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
array([[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1]], dtype=uint8)
# Elliptical Kernel
>>> cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
array([[0, 0, 1, 0, 0],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[0, 0, 1, 0, 0]], dtype=uint8)
# Cross-shaped Kernel
>>> cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
array([[0, 0, 1, 0, 0],
[0, 0, 1, 0, 0],
[1, 1, 1, 1, 1],
[0, 0, 1, 0, 0],
[0, 0, 1, 0, 0]], dtype=uint8)

SyntaxError: invalid syntax (1656624787.py, line 2)